from typing import Protocol
from models.entities import Account

class IRepository(Protocol):
    def save(self, account: Account) -> None: ...
    def get(self, account_id: int) -> Account: ...

class ICalculationStrategy(Protocol):
    def calculate(self, amount: float) -> float: ...

class ICommand(Protocol):
    def execute(self) -> None: ...